import {
  LayoutDashboard,
  Brain,
  Share2,
  Search,
  FileText,
  Plus,
  Boxes,
  UserRound,
  Settings,
  Terminal,
  Check,
  ChevronRight,
  ChevronLeft,
  ExternalLink,
  RefreshCw,
  Trash2,
  Pencil,
  Clock,
  Sparkles,
  Upload,
  Link2,
  Filter,
  X,
  CircleHelp,
  Pin,
  ZoomIn,
  Crosshair,
  SlidersHorizontal,
  Rss,
  type LucideIcon,
} from "lucide-react";

export const Icon = {
  overview: LayoutDashboard,
  memory: Brain,
  timeline: Rss,
  graph: Share2,
  search: Search,
  document: FileText,
  add: Plus,
  forget: X,
  space: Boxes,
  profile: UserRound,
  settings: Settings,
  terminal: Terminal,
  check: Check,
  chevron: ChevronRight,
  back: ChevronLeft,
  external: ExternalLink,
  refresh: RefreshCw,
  trash: Trash2,
  edit: Pencil,
  clock: Clock,
  spark: Sparkles,
  upload: Upload,
  link: Link2,
  filter: Filter,
  help: CircleHelp,
  pin: Pin,
  zoom: ZoomIn,
  crosshair: Crosshair,
  sliders: SlidersHorizontal,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icon;
